# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"
run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace

  settings:
    govet:
      enable-all: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        path: (.+)_test.go
        text: fieldalignment
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - gofumpt
