# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

run:
  timeout: 5m
  go: "1.23.5"
  allow-parallel-runners: true

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - partial-git
    govet:
      enable-all: true
    staticcheck:
      checks: ["all"]
    gosec:
      excludes:
        - G204  # Subprocess launched with variable (common in CLI tools)
    revive:
      rules:
        - name: exported
          arguments: [true]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0